<!-- nobasic - MODIFICAR AGREGAR TEMPLATE.BASIC HTML CSS JS - 
ENTRE INDEX y SHOW de CATEGORIA | PRODUCTO | TIPO
SE VAN A ARMAR LAS VISTAS DEL USUARIO
NO TIENEN POSIBILIDAD DE EDITAR NI BORRAR
MUESTRA VISTA DE CATEGORIAS
 -->